server:
  port: 8085  # Porta onde o microsserviço de usuários está rodando
spring:
  application:
    name: oauth-ms

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true